### ISSUE TITLE
Older version of JQuery

### ISSUE THREAD

**Issue by RahulJha600** [oktadeveloper/rockstar#1]
Hi Team,

We are planning to use rockstar in our Okta setup, while scanning before the use of Rockstar plugin we scan the entire code and found out it is usng an older version of JQuery setup (Version 1.12.4).

We are planning to update the Jquery version to version 3.4+ and wants to know if this require any license to do that.

Can you also let us know if there is any license involved while using at enterprise level.

Let us know if we can make changes in code base and keep it our use as well.

Thanks
Rahul Jha

**Comment by gabrielsroka** [comment]
> Team

haha, it's just me

> jQuery 1.12.4

it's actually a patched version of 1.12.4 (the same one Okta uses on its admin console -- not that Okta is involved in rockstar or vouching for it, but i just want to clarify)

This repo is a copy of https://github.com/gabrielsroka/gabrielsroka.github.io/tree/master/rockstar which has an MIT license https://github.com/gabrielsroka/gabrielsroka.github.io/blob/master/LICENSE

**Comment by RahulJha600** [comment]
Thanks Gabriel..
