### ISSUE TITLE
Architecture Diagram

### ISSUE THREAD

**Issue by RahulJha600** [oktadeveloper/rockstar#3]
Hi Gabrielsroka,

We have been testing rockstar for quite some now and wants to propose it for larger use for team.

For that we are in need to some sort of Architecture diagram (to present ) of it, can you let me know if you have any architecture diagram for Rockstar which we can use.

Let me know if you need any details from us as well.

Thanks in Advance
Regards
Rahul Jha

**Comment by gabrielsroka** [comment]
Hi @RahulJha600 

I'm not an architect, so I don't know what an architecture diagram would look like.

rockstar is a Chrome extension that calls the Okta APIs and renders results in HTML or CSV. It uses jQuery.

Here's a mini-version that's 25 lines long. If you want to draw an architecture diagram of that, I can tell you if it looks right:
https://github.com/gabrielsroka/gabrielsroka.github.io/blob/master/SearchGroups.js
